namespace BBG.Ygo.Network
{
    public static class PlayerProperties
    {
        /// <summary>
        /// Player data json
        /// </summary>
        public const string PLAYER_DATA = "PLAYER_DATA";
        /// <summary>
        /// random integer number generated by host
        /// </summary>
        public const string DUEL_SEED = "DUEL_SEED";
    }
}